# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/upc-pre-202401-Theraphy-SI728-SW81/SpringCloudConfig-GitRepository.git
  # Spring properties in case you use different profiles
  profiles:
    active: dev